version: 2


base: &base
  working_directory: ~/repo
  docker:
    - image: continuumio/miniconda3:latest


test: &test
  <<: *base
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install Docker dependencies
        command: |
          apt-get update
          apt-get install gnupg-agent --yes 
          apt install docker.io --yes
    # - run:
    #     name: Update Conda
    #     command: |

          # conda config --set always_yes True
          # conda config --add channels conda-forge
          # conda install -n base conda
          # conda update --all
          # conda install docker-compose make git git-lfs
          # # conda env create -f environment-${PYTHON_VERSION}.yml
          # # conda install python=${PYTHON_VERSION} -n alertadengue --file requirements-dev.txt
    - run:
        name: Then compile and install GIT
        command: |
          apt-get update
          apt-get install wget
          apt-get install dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev -y
          apt-get install asciidoc xmlto docbook2x -y
          apt-get install install-info -y
          wget https://github.com/git/git/archive/v2.26.0.tar.gz -O docker/git.tar.gz
          tar -zxf docker/git.tar.gz -C docker/
          make configure -C docker/git-2.26.0/
          ./docker/git-2.26.0/configure --prefix=/usr
          make all doc info -C docker/git-2.26.0/
          make install install-doc install-html install-info -C docker/git-2.26.0/
    - run:
        name: LFS --version
        command: |
          apt-get install git-lfs -y
          git --version
          git-lfs --version
    - run:
        name: clone Data repo
        command: |
          #git -C ./docker/ clone https://github.com/AlertaDengue/Data.git
          git lfs clone https://github.com/AlertaDengue/Data.git docker/
    - run:
        name: Rename data file and merge patch
        command: |
          mv docker/Data/ docker/dev_dumps/
          mv docker/dev_dumps/alertademo_data.sql docker/dev_dumps/latest_dengue.sql
          cat ./docker/dev_dumps/patch/notificacao.sql >> docker/dev_dumps/latest_dengue.sql
    - run:
        name: Prepare data file
        command: |
          cat ./docker/dev_dumps/latest_dengue.sql | gzip > ./docker/dev_dumps/latest_dengue.sql.gz
    - run:
        name: Copy env_file as env_staging
        command: cp example_env_file .env_staging
    - run:
        name: make deploy_staging
        command: make deploy_staging
    - run:
        name: Show the exact environment used
        command: |
          source activate alertadengue
          conda list
    - run:
        name: Run Tests
        command: |
          source activate alertadengue
          cd AlertaDengue
          flake8
jobs:
  python37_test:
      <<: *test
      environment:
        - PYTHON_VERSION: 3.7

workflows:
  version: 2
  test:
    jobs:
      - python37_test