# Generated by Django 5.2.11 on 2026-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0005_create_notification_api_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCityCountByUfChikungunya",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "state_name",
                        "disease",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        db_column="uf",
                        help_text="Nome do estado",
                        max_length=128,
                    ),
                ),
                (
                    "disease",
                    models.CharField(
                        db_column="disease", help_text="Doença", max_length=32
                    ),
                ),
                (
                    "city_count",
                    models.IntegerField(
                        db_column="city_count",
                        help_text="Número de municípios monitorados",
                    ),
                ),
            ],
            options={
                "verbose_name": "home chikungunya city count by UF",
                "verbose_name_plural": "home chikungunya city counts by UF",
                "db_table": "city_count_by_uf_chikungunya_materialized_view",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HomeCityCountByUfDengue",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "state_name",
                        "disease",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        db_column="uf",
                        help_text="Nome do estado",
                        max_length=128,
                    ),
                ),
                (
                    "disease",
                    models.CharField(
                        db_column="disease", help_text="Doença", max_length=32
                    ),
                ),
                (
                    "city_count",
                    models.IntegerField(
                        db_column="city_count",
                        help_text="Número de municípios monitorados",
                    ),
                ),
            ],
            options={
                "verbose_name": "home dengue city count by UF",
                "verbose_name_plural": "home dengue city counts by UF",
                "db_table": "city_count_by_uf_dengue_materialized_view",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HomeCityCountByUfZika",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "state_name",
                        "disease",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        db_column="uf",
                        help_text="Nome do estado",
                        max_length=128,
                    ),
                ),
                (
                    "disease",
                    models.CharField(
                        db_column="disease", help_text="Doença", max_length=32
                    ),
                ),
                (
                    "city_count",
                    models.IntegerField(
                        db_column="city_count",
                        help_text="Número de municípios monitorados",
                    ),
                ),
            ],
            options={
                "verbose_name": "home zika city count by UF",
                "verbose_name_plural": "home zika city counts by UF",
                "db_table": "city_count_by_uf_zika_materialized_view",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HomeUfHistoryChikungunya",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "state_abbr",
                        "geocode",
                        "epiweek",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_abbr",
                    models.CharField(
                        db_column="state_abbv",
                        help_text="Sigla do estado",
                        max_length=2,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        db_column="state_name",
                        help_text="Nome do estado",
                        max_length=128,
                    ),
                ),
                (
                    "geocode",
                    models.IntegerField(
                        db_column="municipio_geocodigo",
                        help_text="Código do município",
                    ),
                ),
                (
                    "epiweek",
                    models.IntegerField(
                        db_column="SE",
                        help_text="Semana epidemiológica no formato AAAASS",
                    ),
                ),
                (
                    "epiweek_start",
                    models.DateField(
                        db_column="data_iniSE",
                        help_text="Data inicial da semana epidemiológica",
                    ),
                ),
                (
                    "estimated_cases",
                    models.FloatField(
                        blank=True,
                        db_column="casos_est",
                        help_text="Casos estimados",
                        null=True,
                    ),
                ),
                (
                    "cases",
                    models.IntegerField(
                        blank=True,
                        db_column="casos",
                        help_text="Casos notificados",
                        null=True,
                    ),
                ),
                (
                    "alert_level",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="nivel",
                        help_text="Nível de alerta",
                        null=True,
                    ),
                ),
                (
                    "receptive",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="receptivo",
                        help_text="Indicador de receptividade climática",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "home UF chikungunya history",
                "verbose_name_plural": "home UF chikungunya history",
                "db_table": "hist_uf_chik_materialized_view",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HomeUfHistoryDengue",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "state_abbr",
                        "geocode",
                        "epiweek",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_abbr",
                    models.CharField(
                        db_column="state_abbv",
                        help_text="Sigla do estado",
                        max_length=2,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        db_column="state_name",
                        help_text="Nome do estado",
                        max_length=128,
                    ),
                ),
                (
                    "geocode",
                    models.IntegerField(
                        db_column="municipio_geocodigo",
                        help_text="Código do município",
                    ),
                ),
                (
                    "epiweek",
                    models.IntegerField(
                        db_column="SE",
                        help_text="Semana epidemiológica no formato AAAASS",
                    ),
                ),
                (
                    "epiweek_start",
                    models.DateField(
                        db_column="data_iniSE",
                        help_text="Data inicial da semana epidemiológica",
                    ),
                ),
                (
                    "estimated_cases",
                    models.FloatField(
                        blank=True,
                        db_column="casos_est",
                        help_text="Casos estimados",
                        null=True,
                    ),
                ),
                (
                    "cases",
                    models.IntegerField(
                        blank=True,
                        db_column="casos",
                        help_text="Casos notificados",
                        null=True,
                    ),
                ),
                (
                    "alert_level",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="nivel",
                        help_text="Nível de alerta",
                        null=True,
                    ),
                ),
                (
                    "receptive",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="receptivo",
                        help_text="Indicador de receptividade climática",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "home UF dengue history",
                "verbose_name_plural": "home UF dengue history",
                "db_table": "hist_uf_dengue_materialized_view",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HomeUfHistoryZika",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "state_abbr",
                        "geocode",
                        "epiweek",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_abbr",
                    models.CharField(
                        db_column="state_abbv",
                        help_text="Sigla do estado",
                        max_length=2,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        db_column="state_name",
                        help_text="Nome do estado",
                        max_length=128,
                    ),
                ),
                (
                    "geocode",
                    models.IntegerField(
                        db_column="municipio_geocodigo",
                        help_text="Código do município",
                    ),
                ),
                (
                    "epiweek",
                    models.IntegerField(
                        db_column="SE",
                        help_text="Semana epidemiológica no formato AAAASS",
                    ),
                ),
                (
                    "epiweek_start",
                    models.DateField(
                        db_column="data_iniSE",
                        help_text="Data inicial da semana epidemiológica",
                    ),
                ),
                (
                    "estimated_cases",
                    models.FloatField(
                        blank=True,
                        db_column="casos_est",
                        help_text="Casos estimados",
                        null=True,
                    ),
                ),
                (
                    "cases",
                    models.IntegerField(
                        blank=True,
                        db_column="casos",
                        help_text="Casos notificados",
                        null=True,
                    ),
                ),
                (
                    "alert_level",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="nivel",
                        help_text="Nível de alerta",
                        null=True,
                    ),
                ),
                (
                    "receptive",
                    models.SmallIntegerField(
                        blank=True,
                        db_column="receptivo",
                        help_text="Indicador de receptividade climática",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "home UF zika history",
                "verbose_name_plural": "home UF zika history",
                "db_table": "hist_uf_zika_materialized_view",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
