# Generated by Django 3.0.7 on 2021-03-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FederatedState',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('map_center_x', models.FloatField()),
                ('map_center_y', models.FloatField()),
                ('map_zoom', models.CharField(max_length=3)),
                (
                    'status',
                    models.BooleanField(
                        choices=[(True, 'Enable'), (False, 'Disable')]
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Federated State'},
        ),
    ]
